name: "sqlserver-2017"
description:  Microsoft SQL Server 2017 catalog
version: 0.1
category: service layer
maintainer: Kumar Chockalingam
license: # The license
projectURL: # A URL related to the catalog entry
