name: "dd-nginx-consultemplate"
description:  nginx proxy with consul template configuration catalog
version: 0.1
category: service layer
maintainer: Kumar Chockalingam
license: # The license
projectURL: # A URL related to the catalog entry
