.catalog:
  name: "nginx-consultemplate"
  description: "nginx proxy configuration with Consul Template"
  version: "0.1"
  questions:
    - variable: "consul_service"
      description: "Link to consul service"
      label: "Consul Service"
      type: "service"
      required: true
    - variable: PUBLIC_DNS_HOSTNAME
      label: public dns hostname
      description: |
        E.g: `mci.ci.dimensiondata.cloud`.
      required: true
      type: string
    - variable: CERTBOT_WEBROOT
      label: Certbot Webroot
      description: |
        Webroot to be used by certbot
      required: true
      default: /var/www
      type: string
    - variable: CERTBOT_EMAIL
      label: Your Email Address
      description: |
        Enter the email address to use for creating the Let's Encrypt account.
      required: true
      type: string
    - variable: RENEW_BEFORE_DAYS
      label: Renew Before Days
      description: |
        Number of days left until certificate expiry before the certificate should be renewed
      required: true
      default: 14
      type: int
    - variable: LOOP_TIME
      label: Loop Time
      description: |
        Time between each renewal check
      required: true
      default: 300
      type: int
    - variable: STAGING
      label: Staging API Environment
      description: |
        Should the staging API environment be used for issuing the certificate?
        (Staging should be used for testing purposes only!)
      required: true
      default: true
      type: boolean
    - variable: HOST_CHECK_PORT
      label: Host Check Port
      description: |
        The port on which the loadbalancer expects the requests to the letsencrypt-service.
      required: true
      default: 80
      type: int
    - variable: HOST_CHECK_LOOP_TIME
      label: Host Check Loop Time
      description: |
        Time to sleep before each host check.
      required: true
      default: 10
      type: int
    - variable: STORAGE_DRIVER
      label: Volume Storage Driver (Optional)
      default: rancher-nfs
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (see `Infrastructure -> Storage`). This also requires "Volume Name" to be set.
      required: false
      type: string
    - variable: STORAGE_DRIVER_OPT
      label: Storage Driver Option (Optional)
      description: |
        Specify a single "driver_opts" key/value pair in the format "optionName: optionValue ".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
      required: false
      default: 'onRemove: purge'
      type: string
    - variable: VOLUME_NAME
      label: Volume Name
      description: |
        To store the account data, certificates and private keys in a volume, enter the volume name that should be used.
        By default this will be a (host scoped) named Docker volume. See "Persistent Storage Driver" for other options.
      required: true
      default: letsencrypt-certs
      type: string
version: '2'
services:
  service-lb:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - protocol: https
        service: nginx
        source_port: 443
        target_port: 80
        hostname: ${PUBLIC_DNS_HOSTNAME}
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  cert-lb:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - protocol: http
        service: letsencrypt-nginx
        source_port: 80
        target_port: 80
        hostname: ${PUBLIC_DNS_HOSTNAME}
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000