.catalog:
  name: "nginx-consultemplate"
  description: "nginx proxy configuration with Consul Template"
  version: "0.1"
  questions:
    - variable: "consul_service"
      description: "Link to consul service"
      label: "Consul Service"
      type: "service"
      required: true
    - variable: CERT_NAME
      label: public dns hostname
      description: |
        E.g: `mci.ci.dimensiondata.cloud`.
      required: true
      type: string
version: '2'
services:
  haproxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs:
      - ${CERT_NAME}
      port_rules:
      - protocol: https
        service: nginx
        source_port: 443
        target_port: 80
        hostname: ${CERT_NAME}
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000