version: '2'
services:
  nginx-config:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-config:latest
    environment:
      - configs=$consul_configs
    volumes:
      - /etc/nginx/config
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
  nginx-ssl:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-ssl:latest
    environment:
      - cert=$cert_name
      - apiKey=$apiKey
    volumes:
      - /etc/nginx/ssl
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true

  nginx-log:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /var/log/nginx

  nginx:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-consultemplate:latest
    environment:
      - CONSUL_PORT_8500_TCP_ADDR=consul
      - LOG_LEVEL=debug
      - CONSUL_KV_PREFIX=nginx
      - CONFIG_JSON=/etc/nginx/config/consul_nginx_initial_config.json
      - CONFIG_JSON_LOAD=true  #remove this env variable to not load the ininital settings from json file
      - SERVICE_IGNORE=true
    ports:
      - 80:80
      - 443:443
      - 5671:5671
      - 8080:8080
      - 8081:8081
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
      - 8200:8200
      - 8201:8201
    volumes_from:
      - nginx-config
      - nginx-ssl
      - nginx-log
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: true
      io.rancher.sidekicks: nginx-config,nginx-ssl,nginx-log

  consul-data:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /consul/data

  consul:
    image: artifactory.devops.itaas-cloud.com:6553/consul-base:latest
    environment:
      - SERVICE_IGNORE=true
      - rancher=1
    volumes_from:
      - consul-data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: consul-data

  registrator:
    image: artifactory.devops.itaas-cloud.com:6553/rancher-registrator:latest
    links:
      - consul
    restart: always
    environment:
      - rancher=1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -rancherExternalPorts -cleanup consul://consul:8500
    labels:
      io.rancher.container.dns: 'true'
      com.btfin.devops.name: registrator
      io.rancher.scheduler.global: 'true'
      io.rancher.container.network: 'false'
      io.rancher.container.hostname_override: container_name

  # registrator:
  #   image: artifactory.devops.itaas-cloud.com:6553/registrator-base:latest
  #   depends_on:
  #     - consul
  #   environment:
  #     - rancher=1
  #   tty: true
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   command: consul://consul:8500
  #   links:
  #     - consul
  #   stdin_open: true
  #   labels:
  #     io.rancher.scheduler.global: true
  #     io.rancher.container.hostname_override: container_name

  # registrator-consulkv:
  #   image: artifactory.devops.itaas-cloud.com:6553/registrator-base:latest
  #   depends_on:
  #     - consul
  #   environment:
  #     - rancher=1
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   command: consulkv://consul:8500/v1/kv/service
  #   labels:
  #     io.rancher.container.hostname_override: container_name

  vault:
    image: vault:0.8.1
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - SERVICE_8200_CHECK_HTTP=/v1/sys/seal-status
      - SERVICE_8200_CHECK_INTERVAL=30s
      - SERVICE_8200_CHECK_TIMEOUT=2s
    command: vault server -config=/vault/config/vault.json
    depends_on:
      - consul
    ports:
      - 8200
    volumes_from:
      - vault-config
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: vault-init, vault-config

  vault-config:
    image: artifactory.devops.itaas-cloud.com:6553/vault-config:latest
    volumes:
      - /opt/vault
      - /vault/config
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true

  vault-init:
    image: artifactory.devops.itaas-cloud.com:6553/vault-init:latest
    environment:
      - rancher=1
      - LOCATION_KEY=$location_key
    depends_on:
      - vault
    volumes_from:
      - vault-config
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true

  rabbitmq-config:
    image: artifactory.devops.itaas-cloud.com:6553/rabbitmq-config:latest
    environment:
      - rancher=1
      - RABBITMQ_CLUSTER_PARTITION_HANDLING=autoheal
      - RABBITMQ_NET_TICKTIME=60
      - RABBITMQ_DEFAULT_USER=$rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=$rabbitmq_pass
    volumes_from:
      - rabbitmq-data
    labels:
      io.rancher.container.hostname_override: container_name


  rabbitmq-data:
    image: rabbitmq:3.6.11-management-alpine
    entrypoint: /bin/true
    network_mode: "none"
    volumes:
      - /etc/rabbitmq
      - /opt/rancher/bin
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true

  rabbitmq:
    image: rabbitmq:3.6.11-management-alpine
    environment:
      - rancher=1
      - RABBITMQ_ERLANG_COOKIE=$erlang_cookie
      - RABBITMQ_DEFAULT_USER=$rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=$rabbitmq_pass
      - SERVICE_NAME=rabbitmq-local
      - LOCATION_KEY=$location_key
      - GLOBAL=true
    entrypoint: /opt/rancher/bin/run.sh
    ports:
      - 5672
    volumes_from:
      - rabbitmq-data
    restart: always
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: rabbitmq-data, rabbitmq-config
