version: '2'
services:
  nginx-config:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-config:1.0.8205_7c9fe205
    environment:
      - configs=$consul_configs
    volumes:
      - /etc/nginx/config
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
  nginx-ssl:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-ssl:1.0.8205_7c9fe205
    environment:
      - cert=$cert_name
      - apiKey=$apiKey
    volumes:
      - /etc/nginx/ssl
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true

  nginx-log:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /var/log/nginx
  
  nginx:
    image: artifactory.devops.itaas-cloud.com:6553/nginx-consultemplate:1.0.8205_7c9fe205
    environment:
      - CONSUL_PORT_8500_TCP_ADDR=consul
      - LOG_LEVEL=debug
      - CONSUL_KV_PREFIX=nginx
      - CONFIG_JSON=/etc/nginx/config/consul_nginx_initial_config.json
      - CONFIG_JSON_LOAD=true  #remove this env variable to not load the ininital settings from json file
      - SERVICE_IGNORE=true
    links:
      - consul-1:consul
    ports:
      - 80:80
      - 443:443
      - 5671:5671
      - 8080:8080
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
      - 8200:8200
      - 8201:8201
    volumes_from:
      - nginx-config
      - nginx-ssl
      - nginx-log
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: nginx-config,nginx-ssl,nginx-log
  
  consul-data-1:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /consul/data
  
  consul-data-2:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - /consul/data

  consul-1:
    image: consul:0.7.3
    command: agent -server -bootstrap-expect=$consul_bootstrap_expect -ui-dir /ui -bind 0.0.0.0 -client=0.0.0.0
    environment:
      - SERVICE_IGNORE=true
    volumes_from:
      - consul-data-1
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: consul-data-1
  
  consul-2:
    image: consul:0.7.3
    command: agent -server -join consul-1
    environment:
      - SERVICE_IGNORE=true
    volumes_from:
      - consul-data-2
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: consul-data-2

  vault:
    image: artifactory.devops.itaas-cloud.com:6553/sl3-vault:1.0.8205_7c9fe205
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
    command: vault server -config=/vault/config/vault.json
    links:
      - nginx:consul
    labels:
      io.rancher.container.hostname_override: container_name

  vault-init:
    image: artifactory.devops.itaas-cloud.com:6553/sl3-vault-init:1.0.8205_7c9fe205
    entrypoint:
      - bash
    labels:
      io.rancher.container.hostname_override: container_name
      
  
      