.catalog:
  name: "dd-nginx-consultemplate"
  description: "nginx proxy configuration with Consul Template"
  version: "0.1"
  questions:
    - variable: "consul_service"
      description: "Link to consul service"
      label: "Consul Service"
      type: "service"
      required: true
