version: '2'
services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD} 
      - VAULT_REDIRECT_INTERFACE=eth0
      - SERVICE_1433_NAME=SQL
      - SERVICE_1433_TAGS=tcp-proxy
      - SERVICE_1433_ID=SQL:8200
    external_links:
      - $vault_service:vault
    expose:
      - 1433
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always