.catalog:
  name: "sqlserver-2017"
  description: "service layer sql server"
  version: "0.1"
  questions:
    - variable: "consul_service"
      description: "Link to Consul service"
      label: "Consul Service"
      type: "service"
      required: true
    - variable: "Global"
      description: "Global Environment"
      label: "Is it a Global Environment SQL Server"
      type: "boolean"
      default: true
      required: true
    - variable: "Location_Key"
      description: "Location Key"
      label: "Location Key"
      type: "string"
      default: l01
      required: true
    - variable: "SA_PASSWORD"
      description: "SQL SA PASSWORD"
      label: "SQL SA PASSWORD"
      type: "password"
      required: true
    - variable: STORAGE_DRIVER
      label: Volume Storage Driver
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (see `Infrastructure -> Storage`). This also requires "Volume Name" to be set.
      required: true
      default: rancher-nfs
      type: string
    - variable: VOLUME_NAME
      label: Volume Name
      description: |
        To store the sql data in a volume, enter the volume name that should be used.
      required: true
      default: sqldata
      type: string