version: '2'
services:
  consul-data:
    image: alpine:latest
    entrypoint:
      - /bin/true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
      io.rancher.container.pull_image: always
    volumes:
      - /consul/data
  
  registrator:
    image: gliderlabs/registrator:master
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command:
     - -internal=true
     - -useIpFromLabel=io.rancher.container.ip
     - consul://consul:8500

    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: true
      io.rancher.container.pull_image: always

  consul:
    image: artifactory.devops.itaas-cloud.com:6553/consul-base:latest
    environment:
      - rancher=1
      - SERVICE_TAGS=http-proxy
      - SERVICE_8500_NAME=consulapi
      - SERVICE_8500_TAGS=http-proxy
      - SERVICE_8500_ID=consulapi
      - SERVICE_8300_IGNORE=true
      - SERVICE_8301_IGNORE=true
      - SERVICE_8302_IGNORE=true
      - SERVICE_8600_IGNORE=true
    volumes_from:
      - consul-data
    expose:
      - 8300
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8500
      - 8600
      - 8600/udp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: consul-data
      io.rancher.container.pull_image: always

  